#!/bin/bash

examples_dir=${1:-examples/bin}

echo -e "Running CUDA API wrapper example programs...\n"
ls "$examples_dir" | while read example_file; do 
#	canonical_name=$(readlink -f "$examples_dir/$example_file")
	echo 
	echo -e "--------------------------------"
	echo -e " Example: $example_file" 
	echo -e "--------------------------------\n" 
	$examples_dir/$example_file
done
